# -*- coding: utf-8 -*-
"""projeto-engenharia-de-contexto-e-logica-fisica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMFcQ64kmRE5azkfmUN4eL69ga-tlqEJ
"""

Parte 1
﻿def analisar_clima_do_bairro():
    # Nosso "Mapa de Dados": [Local, Temperatura, Umidade, IQA]
    # O IQA segue a regra brasileira: 0-40 (Bom), 41-80 (Moderado), >80 (Ruim)
    dados_locais = [
        ["Praça das Árvores", 26, 70, 35],       # Fresquinho e ar puro
        ["Cruzamento do Centro", 32, 40, 85],    # Quente e ar pesado (muito carro)
        ["Ponto de Ônibus", 30, 50, 55]          # No meio do caminho
    ]

    print("--- RELATÓRIO DO MINI-CIENTISTA ---")

    for local in dados_locais:
        nome = local[0]
        # Usamos um for interno para "olhar" cada número do local
        for i in range(1, len(local)):
            temp = local[1]
            umid = local[2]
            iqa = local[3]

        # 1. Classificando o ar com o MATCH-CASE (O tradutor do robô)
        match iqa:
            case i if i <= 40:
                classificacao_ar = "Delicioso (Bom)"
            case i if i <= 80:
                classificacao_ar = "Ok, mas evite correr (Moderado)"
            case _:
                classificacao_ar = "Atenção: Use máscara! (Ruim/Péssimo)"

        # 2. A Fórmula Mágica do Conforto (Matemática Complexa)
        # Se a temperatura for longe de 24°C, a nota cai. Se o IQA for alto, a nota cai.
        # Criamos um "desvio" da temperatura ideal
        desvio_temp = abs(temp - 24)
        nota_conforto = 10 - (desvio_temp * 0.5) - (iqa / 20)

        # Garantindo que a nota fique entre 0 e 10
        nota_final = max(0, min(10, nota_conforto))

        print(f"\nLocal: {nome}")
        print(f"-> Qualidade do Ar: {classificacao_ar}")
        print(f"-> Nota de Conforto: {nota_final:.1f}/10")

# Chamando a função para o robô trabalhar!
analisar_clima_do_bairro()

PARTE 2




def simulador_fuga_de_casa():
    # O mapa da nossa aventura
    locais = ["Quarto", "Corredor", "Cozinha", "Varanda", "Rua"]
    estados = ["Livre", "Porta Trancada", "Fumaça", "Caminho Livre", "Saída"]

    posicao = 0 # Onde o agente começa (Quarto)
    inventario = [] # O que o agente está carregando
    energia = 10 # Se chegar a 0, o agente cansa
    concluiu = False

    print("--- INICIANDO PROTOCOLO DE FUGA ---")

    while energia > 0 and not concluiu:
        local_atual = locais[posicao]
        perigo = estados[posicao]

        print(f"Estou no(a) {local_atual}. O que vejo? {perigo}.")

        # Regras de Decisão (O cérebro do agente)
        if perigo == "Livre":
            print("Tudo certo! Pegando a chave reserva por segurança.")
            inventario.append("chave")
            posicao += 1

        elif perigo == "Porta Trancada":
            if "chave" in inventario:
                print("Ufa! Usei a chave que peguei antes. Abrindo...")
                posicao += 1
            else:
                print("Porta trancada e sem chave! Preciso voltar e procurar.")
                posicao -= 1 # Retrocedendo!

        elif perigo == "Fumaça":
            print("Muita fumaça! Vou rastejar devagar (perco energia).")
            energia -= 3
            posicao += 1

        elif perigo == "Caminho Livre":
            print("Caminho livre! Correndo para o final.")
            posicao += 1

        elif perigo == "Saída":
            print("CONSEGUI! Cheguei na Rua!")
            concluiu = True

        energia -= 1 # Cada movimento gasta um pouco de energia
        print(f"Energia restante: {energia}")

    if not concluiu:
        print("O tempo acabou... O agente não conseguiu sair.")

simulador_fuga_de_casa()
PARTE 3
Parágrafo 1: Durante o mapeamento físico da minha casa, percebi que o mundo não é organizado como uma estante de livros. Para nós, uma "porta trancada" é só um detalhe que resolvemos pegando a chave, mas para o computador, isso precisa ser uma regra de "sim ou não". Percebi que o caos da vida real — como um tapete escorregadio ou um cheiro de queimado — precisa ser transformado em nomes e números para que possamos agir de forma inteligente e rápida em uma emergência.

Parágrafo 2: Ao tentar transformar portas e corredores em variáveis lógicas, o maior desafio foi entender que o computador é "cego" para o contexto. Eu tive que pensar em todas as possibilidades antes delas acontecerem. Se eu não dissesse ao código o que fazer quando encontrasse fumaça, o robô ficaria parado olhando para ela. Isso me ensinou que, para resolver problemas difíceis, eu preciso parar de olhar para o "todo" assustador e começar a olhar para cada pequeno degrau do caminho.

Parágrafo 3: Isso me fez refletir que, no meu dia a dia, aprender a programar me ajuda a ser um "detetive da lógica". Agora, quando tenho um problema grande na escola ou em casa, eu não fico só preocupado. Eu instintivamente começo a criar "se/então" na minha cabeça: "Se eu fizer o trabalho agora, então terei a tarde livre; se eu deixar para depois, terei o risco de ficar sem luz". Programar me deu óculos especiais que mostram que qualquer confusão da vida pode ser organizada se a gente quebrar ela em pedaços pequenos e ordens claras.