# -*- coding: utf-8 -*-
"""projeto-sistema-de-auditoria-de-recursos-corporativos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMFcQ64kmRE5azkfmUN4eL69ga-tlqEJ
"""

import time

# ========================
# Decorator de Auditoria
# ========================
def auditor(func):
    """
    Decorator que imprime informações de auditoria antes e depois da execução da função.
    Mede o tempo de execução e exibe os argumentos passados.
    """
    def wrapper(*args, **kwargs):
        print("========== INÍCIO DA AUDITORIA ==========")
        print(f"Função chamada: {func._name_}")
        print(f"Argumentos posicionais: {args}")
        print(f"Argumentos nomeados: {kwargs}")
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Tempo de execução: {end_time - start_time:.6f} segundos")
        print("=========== FIM DA AUDITORIA ===========\n")
        return result
    return wrapper

# ========================
# Estrutura de Dados da Empresa
# ========================
empresa = {
    "Matriz": {
        "TI": {
            "Infraestrutura": 100000,
            "Desenvolvimento": 250000,
        },
        "RH": {
            "Recrutamento": 50000,
            "Treinamento": 30000,
        },
        "Financeiro": {
            "Contabilidade": 70000,
            "Auditoria": 40000,
        },
        "Marketing": {
            "Digital": 90000,
            "Eventos": 60000,
        }
    },
    "Filial_SP": {
        "TI": {
            "Infraestrutura": 50000,
            "Suporte": 30000,
        },
        "RH": {
            "Recrutamento": 20000,
        }
    }
}

# ========================
# Função Recursiva de Cálculo de Orçamento
# ========================
@auditor
def calcular_orcamento(dicionario, *ignore_departamentos, **kwargs):
    """
    Calcula o orçamento total da empresa de forma recursiva.

    Parâmetros:
    - dicionario: Estrutura de dados aninhada (dict)
    - *ignore_departamentos: lista de departamentos a serem ignorados na soma
    - **kwargs: parâmetros adicionais, como moeda_destino e taxa_cambio
    """
    taxa_cambio = kwargs.get("taxa_cambio", 1)  # Default = 1 se não for fornecida
    moeda_destino = kwargs.get("moeda_destino", "USD")

    def soma_orcamento(dic):
        total = 0
        for chave, valor in dic.items():
            # Ignora departamento e todos os sub-departamentos
            if chave in ignore_departamentos:
                continue
            if isinstance(valor, dict):
                total += soma_orcamento(valor)
            else:
                total += valor
        return total

    total = soma_orcamento(dicionario)
    total_convertido = total * taxa_cambio
    print(f"Orçamento total em {moeda_destino}: {total_convertido}")
    return total_convertido

# ========================
# Exemplos de Uso
# ========================
# Exemplo 1: cálculo geral sem ignorar departamentos
calcular_orcamento(empresa, moeda_destino="BRL", taxa_cambio=5.2)

# Exemplo 2: ignorando o departamento de TI e Digital Marketing
calcular_orcamento(empresa, "TI", "Digital", moeda_destino="BRL", taxa_cambio=5.2)