# -*- coding: utf-8 -*-
"""projeto_traduzindo_logica_para_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMFcQ64kmRE5azkfmUN4eL69ga-tlqEJ
"""

1. Função: processar_vendas
def analisar_clima():

  soma_temperaturas = 0.0

  dias_quentes = 0

  alerta_extremo = False



  for dia in range(1, 8):

    temp = float(input(f"Digite a temperatura do dia {dia}: "))

    soma_temperaturas += temp



    if temp > 35.0:

      dias_quentes += 1



    if temp > 45.0 or temp < -5.0:

      alerta_extremo = True



  media = soma_temperaturas / 7



  print(f"Média semanal: {media:.2f}")

  print(f"Dias acima de 35°C: {dias_quentes}")



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")

2. Função: analisar_clima


def analisar_clima():

  soma_temperaturas = 0.0

  dias_quentes = 0

  alerta_extremo = False



  for dia in range(1, 8):

    temp = float(input(f"Digite a temperatura do dia {dia}: "))

    soma_temperaturas += temp



    if temp > 35.0:

      dias_quentes += 1



    if temp > 45.0 or temp < -5.0:

      alerta_extremo = True



  media = soma_temperaturas / 7



  print(f"Média semanal: {media:.2f}")

  print(f"Dias acima de 35°C: {dias_quentes}")



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")

3. Função: sistema_notas_turma


def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos existem na turma? "))



  for j in range(1, total_alunos + 1):

    aluno_nome = input("Nome do aluno: ")

    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))



    media_aluno = (n1 + n2) / 2



    if media_aluno >= 7.0:

      print(f"{aluno_nome}: Aprovado com média {media_aluno:.2f}")

    elif media_aluno >= 5.0:

      print(f"{aluno_nome}: Recuperação (Média: {media_aluno:.2f})")

    else:

      print(f"{aluno_nome}: Reprovado")

4. Função: simulador_poupanca


def simulador_poupanca():

  saldo = float(input("Valor inicial do investimento: "))

  taxa = float(input("Taxa de juros mensal (em %): "))

  meses = int(input("Número de meses da simulação: "))



  for m in range(1, meses + 1):

    aporte = float(input(f"Quanto deseja depositar no mês {m}? (0 para nenhum): "))



    saldo += aporte

    juros = saldo * (taxa / 100)

    saldo += juros



    print(f"Mês {m}: Saldo atualizado = R$ {saldo:.2f}")



    if saldo > 10000.0:

      print(f"Parabéns! Você atingiu a meta de 10k no mês {m}")



  print(f"Resultado final após {meses} meses: R$ {saldo:.2f}")



1. Sobre Tipagem

No Python, a função input() sempre retorna um valor do tipo string (texto).

Se não utilizarmos int() ou float() para converter esse valor, ele continuará sendo tratado como texto.

Isso afeta diretamente as operações matemáticas, pois:

Não é possível somar uma string com um número (gera erro).
O Python pode realizar concatenação de strings, resultando em valores incorretos.
Exemplos:

"10" + "5" resulta em "105" (concatenação)
"10" + 5 gera erro
Portanto, é necessário converter os dados de entrada:

int() para números inteiros
float() para números decimais
2. Sobre Estruturas (range)

Para que o laço conte de 1 até N (incluindo o N) em Python, usamos:

for i in range(1, N + 1):

Isso acontece porque a função range(inicio, fim) inclui o valor inicial, mas não inclui o valor final.

Por exemplo:

range(1, 5) gera os valores: 1, 2, 3 e 4

Por isso, usamos N + 1 para garantir que o último valor seja incluído no laço.

Diferente do pseudocódigo, que normalmente considera o limite final como inclusivo, o Python trabalha com limite superior exclusivo.