# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgBBLpJMRdbxVMfoSSFe_3jogJt4fdWi
"""

1- O (Outliers) é esconde a verdade sobre os outros numeros, por exemplo se você for fazer a media de idade dentro de uma sala de aula e pegar o aluno mais jovem e o mais velho a media de idade vai dar um numero

"irreal". Existe um valor gigante (como o 70) ou um valor muito pequeno, a média é empurrada para longe da realidade. pode dar uma media de "20", mas naquela sala so tem crianças e a professora de 60 anos. Com isso se não tomarmos cuidado com esses dados, nossas definições de dados estarão sempre fora da realidade.

2- Como dito na pergunta anterior, as vezes os dados (numeros) podem ser muito discrepantes então para ter um resultado justo e mais preciso, tiramos os dados das pontas e pegamos o do meio, que acaba se tornando o numero mais real.

3- A margem de tolerância basicamente é um limite que as empresas entre outros colocam para a falta de algum numero.

ex: uma empresa esta esperando receber 15.000.00 mil porem ela recebe apenas 14.990.00 esses 10 reais estava na margem de tolerância deles, então nao sera uma problema ao ponto de parar a empresa toda para procurar onde foi perdido esse dinheiro.

atividade 2

# Configuração Global

LIMITE_SEGURANCA = 10000.00



# Entrada de Dados com casting

venda1 = float(input("primeira venda: R$ "))

venda2 = float(input("segunda venda : R$ "))

venda3 = float(input("terceira venda : R$ "))



# Função de processamento

def analisar_vendas(v1, v2, v3):

  global LIMITE_SEGURANCA



  # Cálculo da média

  media = (v1 + v2 + v3) / 3



  print(f"\nMédia das vendas: R$ {media:.2f}")



  # Permitir ajuste do limite se necessário

  if v1 > LIMITE_SEGURANCA or v2 > LIMITE_SEGURANCA or v3 > LIMITE_SEGURANCA:

    resposta = input("Venda alta detectada. Deseja ajustar o LIMITE_SEGURANCA? (s/n): ")

    if resposta.lower() == 's':

      novo_limite = float(input("Digite o novo limite: R$ "))

      LIMITE_SEGURANCA = novo_limite

      print(f"Novo LIMITE_SEGURANCA definido: R$ {LIMITE_SEGURANCA:.2f}")



  # Lógica de investigação

  if media > LIMITE_SEGURANCA:

    print("⚠️ SISTEMA EM QUARENTENA")



  # Verificar discrepância (5x maior que a média)

  for venda in [v1, v2, v3]:

    if venda > media * 5:

      print("⚠️ REVISÃO MANUAL NECESSÁRIA")

      break



  # Exibição dos tipos de dados

  print("\n--- Tipos de Dados ---")

  print(f"venda1: {type(v1)}")

  print(f"venda2: {type(v2)}")

  print(f"venda3: {type(v3)}")

  print(f"media: {type(media)}")

  print(f"LIMITE_SEGURANCA: {type(LIMITE_SEGURANCA)}")



# Chamada da função

analisar_vendas(venda1, venda2, venda3)

Primeira venda: R$ 100
Segunda venda: R$ 200
Terceira venda: R$ 5000

Média das vendas: R$ 1766.67

--- Tipos de Dados ---
venda1: <class 'float'>
venda2: <class 'float'>
venda3: <class 'float'>
media: <class 'float'>
LIMITE_SEGURANCA: <class 'float'>

atividade 3
1) A média foi calculada certinho, dando 530.6666. Esse monte de número depois da vírgula não é erro — é só porque o Python usa o tipo float, que mostra mais casas decimais por padrão.


2) Usar uma variável global nesse caso é perigoso porque qualquer parte do sistema pode alterar o valor do limite de segurança sem controle. Em um banco real, isso poderia causar erros graves, como liberar operações arriscadas ou bloquear transições legítimas.


3) Um erro bem frustrante foi de identificação principalmente dentro dos (if, print,) com isso o Python interpretou tudo fora de condição.